#include "images.h"

const ext_img_desc_t images[32] = {
    { "dianchi", &img_dianchi },
    { "wifi", &img_wifi },
    { "shijianjiaozhun", &img_shijianjiaozhun },
    { "liangdu", &img_liangdu },
    { "stationary", &img_stationary },
    { "Walk", &img_walk },
    { "Bike", &img_bike },
    { "Car", &img_car },
    { "Bus", &img_bus },
    { "Subway", &img_subway },
    { "bingshan", &img_bingshan },
    { "bingshangao", &img_bingshangao },
    { "fish01_base", &img_fish01_base },
    { "fish01_lock", &img_fish01_lock },
    { "fish02_base", &img_fish02_base },
    { "fish02_lock", &img_fish02_lock },
    { "fish03_base", &img_fish03_base },
    { "fish03_lock", &img_fish03_lock },
    { "fish04_lock", &img_fish04_lock },
    { "fish04_base", &img_fish04_base },
    { "fish05_base", &img_fish05_base },
    { "fish05_lock", &img_fish05_lock },
    { "fish06_lock", &img_fish06_lock },
    { "fish06_base", &img_fish06_base },
    { "fish07_lock", &img_fish07_lock },
    { "fish07_base", &img_fish07_base },
    { "fish08_base", &img_fish08_base },
    { "fish08_lock", &img_fish08_lock },
    { "fish09_base", &img_fish09_base },
    { "fish09_lock", &img_fish09_lock },
    { "fish10_base", &img_fish10_base },
    { "fish10_lock", &img_fish10_lock },
};
