// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: ecostepv1

#include "ui.h"
#include "ui_helpers.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if (LV_COLOR_DEPTH != 24) && (LV_COLOR_DEPTH != 32)
    #error "LV_COLOR_DEPTH should be 24 or 32 to match the display pipeline"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_scrhome_screen_init();
    vTaskDelay(pdMS_TO_TICKS(1));
    ui_scrcarbon_screen_init();
    vTaskDelay(pdMS_TO_TICKS(1));
    ui_scrbadge_screen_init();
    vTaskDelay(pdMS_TO_TICKS(1));
    ui_scrsettings_screen_init();
    vTaskDelay(pdMS_TO_TICKS(1));
    ui_Calendar_screen_init();
    vTaskDelay(pdMS_TO_TICKS(1));
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_scrhome);
}

void ui_destroy(void)
{
    ui_scrhome_screen_destroy();
    ui_scrcarbon_screen_destroy();
    ui_scrbadge_screen_destroy();
    ui_scrsettings_screen_destroy();
    ui_Calendar_screen_destroy();
}
