// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: ecostepv1

#ifndef _ECOSTEPV1_UI_H
#define _ECOSTEPV1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_scrhome.h"
#include "screens/ui_scrcarbon.h"
#include "screens/ui_scrbadge.h"
#include "screens/ui_scrsettings.h"
#include "screens/ui_Calendar.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bingshan1_png);    // assets/bingshan1.png
LV_IMG_DECLARE(ui_img_group_2_png);    // assets/Group 2.png
LV_IMG_DECLARE(ui_img_1315293343);    // assets/向下2 (1).png
LV_IMG_DECLARE(ui_img_2145288589);    // assets/蓝牙.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
