// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: ecostepv1

#include "../ui.h"

lv_obj_t * ui_Calendar;
lv_obj_t * ui_Calendar2;

// event funtions
void ui_event_Calendar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_scrhome, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_scrhome_screen_init);
    }
}

// build funtions

void ui_Calendar_screen_init(void)
{
    ui_Calendar = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Calendar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Calendar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Calendar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Calendar2 = lv_calendar_create(ui_Calendar);
    lv_calendar_set_today_date(ui_Calendar2, 2025, 12, 30);
    lv_calendar_set_showed_date(ui_Calendar2, 2025, 12);
    lv_obj_t * ui_Calendar2_header = lv_calendar_header_arrow_create(ui_Calendar2);
    lv_obj_set_width(ui_Calendar2, 301);
    lv_obj_set_height(ui_Calendar2, 324);
    lv_obj_set_x(ui_Calendar2, 0);
    lv_obj_set_y(ui_Calendar2, -1);
    lv_obj_set_align(ui_Calendar2, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Calendar, ui_event_Calendar, LV_EVENT_ALL, NULL);

}

void ui_Calendar_screen_destroy(void)
{
    if(ui_Calendar) lv_obj_del(ui_Calendar);

    // NULL screen variables
    ui_Calendar = NULL;
    ui_Calendar2 = NULL;

}
