// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: ecostepv1

#ifndef UI_CALENDAR_H
#define UI_CALENDAR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Calendar
extern void ui_Calendar_screen_init(void);
extern void ui_Calendar_screen_destroy(void);
extern void ui_event_Calendar(lv_event_t * e);
extern lv_obj_t * ui_Calendar;
extern lv_obj_t * ui_Calendar2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

