// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: ecostepv1

#include "../ui.h"

lv_obj_t * ui_scrbadge;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Image10;
lv_obj_t * ui_Image12;

// event funtions
void ui_event_Image12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrhome, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 300, 0, &ui_scrhome_screen_init);
    }
}

// build funtions

void ui_scrbadge_screen_init(void)
{
    ui_scrbadge = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scrbadge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrbadge, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrbadge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_button_create(ui_scrbadge);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -261);
    lv_obj_set_y(ui_Button1, 301);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_image_create(ui_scrbadge);
    lv_image_set_src(ui_Image10, &ui_img_group_2_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 466
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 466
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_image_create(ui_scrbadge);
    lv_image_set_src(ui_Image12, &ui_img_1315293343);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 77
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 77
    lv_obj_set_x(ui_Image12, 0);
    lv_obj_set_y(ui_Image12, -199);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image12, 77);

    lv_obj_add_event_cb(ui_Image12, ui_event_Image12, LV_EVENT_ALL, NULL);

}

void ui_scrbadge_screen_destroy(void)
{
    if(ui_scrbadge) lv_obj_del(ui_scrbadge);

    // NULL screen variables
    ui_scrbadge = NULL;
    ui_Button1 = NULL;
    ui_Image10 = NULL;
    ui_Image12 = NULL;

}
