// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: ecostepv1

#include "../ui.h"

lv_obj_t * ui_scrhome;
lv_obj_t * ui_imgiceberg;
lv_obj_t * ui_lbltime;
lv_obj_t * ui_lblmode;
lv_obj_t * ui_Arc2;
lv_obj_t * ui_Button4;

// event funtions
void ui_event_scrhome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_scrcarbon, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_scrcarbon_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_scrsettings, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_scrsettings_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Calendar, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Calendar_screen_init);
    }
}

void ui_event_imgiceberg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrbadge, LV_SCR_LOAD_ANIM_OVER_TOP, 300, 0, &ui_scrbadge_screen_init);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrbadge, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_scrbadge_screen_init);
    }
}

// build funtions

void ui_scrhome_screen_init(void)
{
    ui_scrhome = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scrhome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrhome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrhome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgiceberg = lv_image_create(ui_scrhome);
    lv_image_set_src(ui_imgiceberg, &ui_img_bingshan1_png);
    lv_obj_set_width(ui_imgiceberg, LV_SIZE_CONTENT);   /// 466
    lv_obj_set_height(ui_imgiceberg, LV_SIZE_CONTENT);    /// 466
    lv_obj_set_align(ui_imgiceberg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgiceberg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgiceberg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbltime = lv_label_create(ui_scrhome);
    lv_obj_set_width(ui_lbltime, LV_SIZE_CONTENT);   /// 233
    lv_obj_set_height(ui_lbltime, LV_SIZE_CONTENT);    /// 233
    lv_obj_set_x(ui_lbltime, 0);
    lv_obj_set_y(ui_lbltime, -111);
    lv_obj_set_align(ui_lbltime, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_lbltime, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_lbltime, "12:34");
    lv_obj_set_style_text_font(ui_lbltime, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblmode = lv_label_create(ui_scrhome);
    lv_obj_set_width(ui_lblmode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblmode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblmode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblmode, "STILL");
    lv_obj_set_style_text_font(ui_lblmode, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc2 = lv_arc_create(ui_scrhome);
    lv_obj_set_width(ui_Arc2, 400);
    lv_obj_set_height(ui_Arc2, 400);
    lv_obj_set_align(ui_Arc2, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc2, 40);
    lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0x84D49D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0xBFC081), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Button4 = lv_button_create(ui_scrhome);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 31);
    lv_obj_set_x(ui_Button4, 2);
    lv_obj_set_y(ui_Button4, 207);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_imgiceberg, ui_event_imgiceberg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_scrhome, ui_event_scrhome, LV_EVENT_ALL, NULL);

}

void ui_scrhome_screen_destroy(void)
{
    if(ui_scrhome) lv_obj_del(ui_scrhome);

    // NULL screen variables
    ui_scrhome = NULL;
    ui_imgiceberg = NULL;
    ui_lbltime = NULL;
    ui_lblmode = NULL;
    ui_Arc2 = NULL;
    ui_Button4 = NULL;

}
