// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: ecostepv1

#include "../ui.h"

lv_obj_t * ui_scrsettings;
lv_obj_t * ui_Slider1;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Dropdown1;
lv_obj_t * ui_Switch1;
lv_obj_t * ui_Switch2;
lv_obj_t * ui_Image13;
lv_obj_t * ui_Image14;

// event funtions
void ui_event_scrsettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_scrhome, LV_SCR_LOAD_ANIM_OVER_TOP, 500, 0, &ui_scrhome_screen_init);
    }
}

// build funtions

void ui_scrsettings_screen_init(void)
{
    ui_scrsettings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scrsettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider1 = lv_slider_create(ui_scrsettings);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 222);
    lv_obj_set_height(ui_Slider1, 21);
    lv_obj_set_x(ui_Slider1, 78);
    lv_obj_set_y(ui_Slider1, -4);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x686868), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider1,
                                                                                              lv_obj_get_style_pad_right(ui_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label4 = lv_label_create(ui_scrsettings);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -126);
    lv_obj_set_y(ui_Label4, -4);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Brightness");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown1 = lv_dropdown_create(ui_scrsettings);
    lv_dropdown_set_options(ui_Dropdown1, "Option 1\nOption 2\nOption 3");
    lv_obj_set_width(ui_Dropdown1, 150);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, -392);
    lv_obj_set_y(ui_Dropdown1, 150);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Switch1 = lv_switch_create(ui_scrsettings);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, -49);
    lv_obj_set_y(ui_Switch1, -132);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    ui_Switch2 = lv_switch_create(ui_scrsettings);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, 100);
    lv_obj_set_y(ui_Switch2, -132);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    ui_Image13 = lv_image_create(ui_scrsettings);
    lv_image_set_src(ui_Image13, &ui_img_2145288589);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image13, 35);
    lv_obj_set_y(ui_Image13, -132);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image13, 50);

    ui_Image14 = lv_image_create(ui_scrsettings);
    lv_image_set_src(ui_Image14, &ui_img_wifi_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image14, -120);
    lv_obj_set_y(ui_Image14, -132);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image14, 50);

    lv_obj_add_event_cb(ui_scrsettings, ui_event_scrsettings, LV_EVENT_ALL, NULL);

}

void ui_scrsettings_screen_destroy(void)
{
    if(ui_scrsettings) lv_obj_del(ui_scrsettings);

    // NULL screen variables
    ui_scrsettings = NULL;
    ui_Slider1 = NULL;
    ui_Label4 = NULL;
    ui_Dropdown1 = NULL;
    ui_Switch1 = NULL;
    ui_Switch2 = NULL;
    ui_Image13 = NULL;
    ui_Image14 = NULL;

}
