// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: ecostepv1

#ifndef UI_SCRHOME_H
#define UI_SCRHOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrhome
extern void ui_scrhome_screen_init(void);
extern void ui_scrhome_screen_destroy(void);
extern void ui_event_scrhome(lv_event_t * e);
extern lv_obj_t * ui_scrhome;
extern void ui_event_imgiceberg(lv_event_t * e);
extern lv_obj_t * ui_imgiceberg;
extern lv_obj_t * ui_lbltime;
extern lv_obj_t * ui_lblmode;
extern lv_obj_t * ui_Arc2;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

