// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: ecostepv1

#ifndef UI_SCRCARBON_H
#define UI_SCRCARBON_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrcarbon
extern void ui_scrcarbon_screen_init(void);
extern void ui_scrcarbon_screen_destroy(void);
extern void ui_event_scrcarbon(lv_event_t * e);
extern lv_obj_t * ui_scrcarbon;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Chart1_Xaxis;
extern lv_obj_t * ui_Chart1_Yaxis1;
extern lv_obj_t * ui_Chart1_Yaxis2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

