// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: ecostepv1

#ifndef UI_SCRSETTINGS_H
#define UI_SCRSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrsettings
extern void ui_scrsettings_screen_init(void);
extern void ui_scrsettings_screen_destroy(void);
extern void ui_event_scrsettings(lv_event_t * e);
extern lv_obj_t * ui_scrsettings;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Image14;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

