// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: ecostepv1

#ifndef UI_SCRBADGE_H
#define UI_SCRBADGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrbadge
extern void ui_scrbadge_screen_init(void);
extern void ui_scrbadge_screen_destroy(void);
extern lv_obj_t * ui_scrbadge;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Image10;
extern void ui_event_Image12(lv_event_t * e);
extern lv_obj_t * ui_Image12;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

